[package]
name = "laminator_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.2"
rp-pico = "0.5.0"
panic-halt = "0.2.0"
embedded-hal ="0.2.7"
cortex-m-rt = "0.7.1" 

[dev-dependencies]

[features]